FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p static media

COPY core/ ./core/
COPY migo/ ./migo/
COPY tg_bot/ ./tg_bot/
COPY manage.py .

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=migo.settings
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "migo.wsgi:application"]
