import os
import django

# Настройка Django окружения
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'migo.settings')
django.setup()
from core.models import ServiceItem

# Данные для автоматического заполнения
translations_data = {
    "passport": {
        "title_uz": "Pasport tarjimasi",
        "title_tg": "Тарҷумаи шиноснома",
        "title_kg": "Паспорттун котормосу",
        "title_kz": "Төлқұжат аудармасы",
        "short_description_uz": "Rossiyada ishlash uchun patent olishda zarur bo'lgan pasportning notarial tasdiqlangan tarjimasi.",
        "short_description_tg": "Тарҷумаи нотариалии шиноснома, ки барои гирифтани патенти корӣ дар Русия зарур аст.",
        "short_description_kg": "РФда иштөөгө патент алуу үчүн зарыл болгон паспорттун нотариалдык котормосу.",
        "short_description_kz": "Ресейде жұмыс істеуге патент алу үшін қажетті төлқұжаттың нотариалды аудармасы.",
        "full_description_uz": "SNILS yaratish va Gosuslugi hisobini ochish uchun zarur bo'lgan pasportning notarial tasdiqlangan tarjimasi. Bu legallashtirish va biometriya topshirish jarayonining boshlang'ich hujjatidir.",
        "full_description_tg": "Тарҷумаи нотариалии шиноснома, ки барои сохтани СНИЛС ва ҳисоби Госуслуги лозим аст. Ин ҳуҷҷати ибтидоӣ барои оғози раванди қонунӣ гардонидан ва супоридани биометрия мебошад.",
        "full_description_kg": "СНИЛСти түзүү жана Мамлекеттик кызматтарда (Госуслуги) эсеп жазуусун ачуу үчүн зарыл болгон паспорттун нотариалдык котормосу. Бул мыйзамдаштыруу жана биометрияны тапшыруу процессин баштоо үчүн баштапкы документ болуп саналат.",
        "full_description_kz": "СНИЛС құру және Госуслуги есебін ашу үшін қажетті төлқұжаттың нотариалды аудармасы. Бұл заңдастыру және биометрияны тапсыру процесін бастау үшін бастапқы құжат болып табылады.",
        "documents_required_uz": "Pasport asl nusxasi\nMigratsiya kartasi",
        "documents_required_tg": "Асли шиноснома\nКорти муҳоҷиратӣ",
        "documents_required_kg": "Паспорттун түп нускасы\nМиграциялык карта",
        "documents_required_kz": "Төлқұжат түпнұсқасы\nКөші-қон картасы",
        "processing_time_uz": "1 ish kuni",
        "processing_time_tg": "1 рӯзи корӣ",
        "processing_time_kg": "1 жумушчу күн",
        "processing_time_kz": "1 жұмыс күні",
        "price_conditions_uz": "1 000 dan 2 000 ₽ gacha",
        "price_conditions_tg": "аз 1 000 то 2 000 ₽",
        "price_conditions_kg": "1 000 - 2 000 ₽ чейин",
        "price_conditions_kz": "1 000 - 2 000 ₽ дейін"
    },
    "sim": {
        "title_uz": "SIM-karta",
        "title_tg": "Сим-корт",
        "title_kg": "SIM-карта",
        "title_kz": "SIM-карта",
        "short_description_uz": "Chet el fuqarolari uchun to'liq hujjatlar to'plami bilan Rossiya SIM-kartasini rasmiylashtirish.",
        "short_description_tg": "Бақайдгирии сим-корти русӣ бо маҷмӯи пурраи ҳуҷҷатҳо барои шаҳрвандони хориҷӣ.",
        "short_description_kg": "Чет өлкөлүк жарандар үчүн документтердин толук топтому менен россиялык SIM-картаны каттоо.",
        "short_description_kz": "Шетелдік азаматтар үшін құжаттардың толық пакетімен ресейлік SIM-картаны ресімдеу.",
        "full_description_uz": "Abonent telefonining apparat IMEI kodiga bog'langan va EBS orqali majburiy verifikatsiyadan o'tgan Rossiya SIM-kartasini rasmiylashtirish. Bir chet el fuqarosi uchun 10 tadan ortiq faol raqam bo'lmasligi qat'iy cheklangan.",
        "full_description_tg": "Бақайдгирии сим-корти русӣ бо пайвастшавӣ ба коди IMEI-и телефони муштарӣ ва санҷиши ҳатмӣ тавассути ЕБС. Маҳдудияти давлатӣ ба назар гирифта мешавад — на бештар аз 10 рақами фаъол барои як шаҳрванди хориҷӣ.",
        "full_description_kg": "Абоненттин телефонунун аппаратуралык IMEI кодуна туташтырылган жана ЕБС аркылуу милдеттүү верификацияланган россиялык SIM-картаны каттоо. Бир чет өлкөлүк жаранга 10дон ашык активдүү номер берилбеши керек деген катуу мамлекеттик чектөө эске алынат.",
        "full_description_kz": "Абонент телефонының аппараттық IMEI кодына байланыстырылған және ЕБС арқылы міндетті верификацияланған ресейлік SIM-картаны ресімдеу. Бір шетелдік азаматқа 10-нан астам белсенді нөмір берілмеуі тиіс деген қатаң мемлекеттік шектеу ескеріледі.",
        "documents_required_uz": "Pasport asl nusxasi\nPasport tarjimasi\nSNILS (yoki elektron pochta)\nEBSda ro'yxatdan o'tgan biometriya\nTelefon (IMEI qayd etish uchun)",
        "documents_required_tg": "Асли шиноснома\nТарҷумаи шиноснома\nСНИЛС (ё почтаи электронӣ)\nБиометрияи дар ЕБС сабтшуда\nТелефон (барои сабти IMEI)",
        "documents_required_kg": "Паспорттун түп нускасы\nПаспорттун котормосу\nСНИЛС (же электрондук почта)\nЕБСте катталган биометрия\nТелефон (IMEIди каттоо үчүн)",
        "documents_required_kz": "Төлқұжат түпнұсқасы\nТөлқұжат аудармасы\nСНИЛС (немесе электрондық пошта)\nЕБС-те тіркелген биометрия\nТелефон (IMEI-ді тіркеу үшін)",
        "processing_time_uz": "10-15 daqiqa (tayyor biometriya bo'lsa)",
        "processing_time_tg": "10-15 дақиқа (дар сурати мавҷуд будани биометрия)",
        "processing_time_kg": "10-15 мүнөт (даяр биометрия болсо)",
        "processing_time_kz": "10-15 минут (дайын биометрия болса)",
        "price_conditions_uz": "Bepul",
        "price_conditions_tg": "Ройгон",
        "price_conditions_kg": "Акысыз",
        "price_conditions_kz": "Тегін"
    },
    "biometrics": {
        "title_uz": "Biometriya (foto + barmoq izlari)",
        "title_tg": "Биометрия (акс + изи ангушт)",
        "title_kg": "Биометрия (сүрөт + манжа издери)",
        "title_kz": "Биометрия (фото + саусақ іздері)",
        "short_description_uz": "Migratsiya hisobi uchun daktiloskopiya va suratga olish jarayonidan o'tish.",
        "short_description_tg": "Гузаштани расмиёти дактилоскопия ва аксбардорӣ барои бақайдгирии муҳоҷират.",
        "short_description_kg": "Миграциялык каттоо үчүн дактилоскопия жана сүрөткө түшүү процедурасынан өтүү.",
        "short_description_kz": "Көші-қон есебі үшін дактилоскопия мен фотосуретке түсу процедурасынан өту.",
        "full_description_uz": "Yagona Biometrik Tizimga (EBS) integratsiya qilish uchun vakolatli banklar bo'limlari orqali 'tasdiqlangan' biometriyani olishda yordam. Bu maqom 5 yil davomida amal qiladi va aloqa hamda moliya xizmatlaridan foydalanish uchun juda muhimdir.",
        "full_description_tg": "Кӯмак дар гирифтани биометрияи «тасдиқшуда» тавассути бахшҳои бонкҳои ваколатдор барои ворид шудан ба Системаи ягонаи биометрӣ (ЕБС). Ин мақом 5 сол амал мекунад ва барои дастрасӣ ба алоқа ва молия хеле муҳим аст.",
        "full_description_kg": "Бирдиктүү биометриялык системага (ЕБС) интеграциялоо үчүн ыйгарым укуктуу банктардын бөлүмдөрү аркылуу 'ырасталган' биометрияны алууга көмөктөшүү. Бул статус 5 жыл бою күчүндө болот жана байланыш жана каржы кызматтарына жетүү үчүн абдан маанилүү.",
        "full_description_kz": "Бірыңғай биометриялық жүйеге (ЕБС) интеграциялану үшін уәкілетті банктердің бөлімшелері арқылы «расталған» биометрияны алуға көмектесу. Бұл статус 5 жыл бойы күшінде болады және байланыс пен қаржы қызметтеріне қол жеткізу үшін өте маңызды.",
        "documents_required_uz": "Pasport asl nusxasi\nPasport tarjimasi\nSNILS\nGosuslugi'da tasdiqlangan hisob",
        "documents_required_tg": "Асли шиноснома\nТарҷумаи шиноснома\nСНИЛС\nҲисоби тасдиқшуда дар Госуслуги",
        "documents_required_kg": "Паспорттун түп нускасы\nПаспорттун котормосу\nСНИЛС\nМамлекеттик кызматтарда (Госуслуги) ырасталган эсеп жазуусу",
        "documents_required_kz": "Төлқұжат түпнұсқасы\nТөлқұжат аудармасы\nСНИЛС\nГосуслуги жүйесінде расталған есеп жазуы",
        "processing_time_uz": "Bankka murojaat qilgan vaqtda",
        "processing_time_tg": "Ҳангоми муроҷиат ба бонк",
        "processing_time_kg": "Банкка кайрылган учурда",
        "processing_time_kz": "Банкке жүгінген сәтте",
        "price_conditions_uz": "Bepul",
        "price_conditions_tg": "Ройгон",
        "price_conditions_kg": "Акысыз",
        "price_conditions_kz": "Тегін"
    },
    "bank_card": {
        "title_uz": "Bank kartasi",
        "title_tg": "Корти бонкӣ",
        "title_kg": "Банк картасы",
        "title_kz": "Банк картасы",
        "short_description_uz": "Rossiya bankida hisob raqami ochish va karta rasmiylashtirishda yordam.",
        "short_description_tg": "Кӯмак дар кушодани суратҳисоби бонкӣ ва гирифтани корт дар бонки Русия.",
        "short_description_kg": "Россия банкында эсеп ачууга жана карта алууга көмөктөшүү.",
        "short_description_kz": "Ресей банкінде шот ашуға және карта алуға көмектесу.",
        "full_description_uz": "Majburiy biometriya topshirish bilan bank hisob raqamlarini ochish. Bankning antifrod-nazoratidan o'tgan holda uyga qonuniy o'tkazmalar uchun Tezkor To'lovlar Tizimiga (SBP) ulanish.",
        "full_description_tg": "Кушодани суратҳисобҳои бонкӣ бо супоридани ҳатмии биометрия. Пайвастшавӣ ба Системаи пардохтҳои фаврӣ (СБП) барои интиқоли пул ба хона бо гузаштани назорати зидди қаллобии бонк.",
        "full_description_kg": "Милдеттүү биометрияны тапшыруу менен банктык эсептерди ачуу. Банктын антифрод-контролунан өтүү менен үйгө мыйзамдуу акча которуулар үчүн Ыкчам төлөмдөр системасына (СБП) туташуу.",
        "full_description_kz": "Міндетті биометрияны тапсырумен банктік шоттарды ашу. Банктің антифрод-бақылауынан өте отырып, үйге заңды аударымдар жасау үшін Жылдам төлемдер жүйесіне (СБП) қосылу.",
        "documents_required_uz": "Pasport asl nusxasi\nPasport tarjimasi\nSNILS\nMigratsiya kartasi\nTasdiqlangan biometriya",
        "documents_required_tg": "Асли шиноснома\nТарҷумаи шиноснома\nСНИЛС\nКорти муҳоҷиратӣ\nБиометрияи тасдиқшуда",
        "documents_required_kg": "Паспорттун түп нускасы\nПаспорттун котормосу\nСНИЛС\nМиграциялык карта\nЫрасталган биометрия",
        "documents_required_kz": "Төлқұжат түпнұсқасы\nТөлқұжат аудармасы\nСНИЛС\nКөші-қон картасы\nРасталған биометрия",
        "processing_time_uz": "1 kundan 3 kungacha",
        "processing_time_tg": "Аз 1 то 3 рӯз",
        "processing_time_kg": "1 күндөн 3 күнгө чейин",
        "processing_time_kz": "1 күннен 3 күнге дейін",
        "price_conditions_uz": "Bepul",
        "price_conditions_tg": "Ройгон",
        "price_conditions_kg": "Акысыз",
        "price_conditions_kz": "Тегін"
    },
    "dms": {
        "title_uz": "Ixtiyoriy tibbiy sug'urta (ПМС/ДМС)",
        "title_tg": "Суғуртаи тиббии ихтиёрӣ (ДМС)",
        "title_kg": "Ыктыярдуу медициналык камсыздандыруу (ДМС)",
        "title_kz": "Ерікті медициналық сақтандыру (ЕЖС/ДМС)",
        "short_description_uz": "Chet el fuqarolari uchun ixtiyoriy tibbiy sug'urta polisini rasmiylashtirish.",
        "short_description_tg": "Бақайдгирии полиси суғуртаи тиббии ихтиёрӣ барои шаҳрвандони хориҷӣ.",
        "short_description_kg": "Чет өлкөлүк жарандар үчүн ыктыярдуу медициналык камсыздандыруу полисин каттоо.",
        "short_description_kz": "Шетелдік азаматтар үшін ерікті медициналық сақтандыру полисін ресімдеу.",
        "full_description_uz": "Qat'iy talablarga muvofiq majburiy ixtiyoriy tibbiy sug'urta (DMS) polisini rasmiylashtirish: eng kam sug'urta qoplamasi summasi roppa-rosa 100 000 rublni tashkil qilishi kerak. Polisi Rossiyada ishlash uchun patent olish uchun qat'iyan zarur.",
        "full_description_tg": "Бақайдгирии полиси ҳатмии ДМС бо риояи қатъии талабот: маблағи ҳадди ақали фарогирии суғурта бояд дақиқан 100 000 рублро ташкил диҳад. Полис барои гирифтани патент барои кор дар Русия қатъиян зарур аст.",
        "full_description_kg": "Катуу талаптарга ылайык милдеттүү ДМС полисин каттоо: камсыздандыруунун эң аз суммасы 100 000 рублду түзүшү керек. Полис РФда иштөөгө патент алуу үчүн катуу талап кылынат.",
        "full_description_kz": "Қатаң талаптарға сәйкес міндетті ЕЖС (ДМС) полисін ресімдеу: сақтандыру төлемінің ең аз сомасы тура 100 000 рубль болуы тиіс. Полис Ресейде жұмыс істеуге патент алу үшін қатаң түрде қажет.",
        "documents_required_uz": "Pasport asl nusxasi\nPasport tarjimasi\nMigratsiya kartasi\nRo'yxatdan o'tganlik hujjati",
        "documents_required_tg": "Асли шиноснома\nТарҷумаи шиноснома\nКорти муҳоҷиратӣ\nБақайдгирӣ",
        "documents_required_kg": "Паспорттун түп нускасы\nПаспорттун котормосу\nМиграциялык карта\nКаттоо",
        "documents_required_kz": "Төлқұжат түпнұсқасы\nТөлқұжат аудармасы\nКөші-қон картасы\nТіркеу",
        "processing_time_uz": "15-20 daqiqa",
        "processing_time_tg": "15-20 дақиқа",
        "processing_time_kg": "15-20 мүнөт",
        "processing_time_kz": "15-20 минут",
        "price_conditions_uz": "yiliga 1 850 dan 4 000 ₽ gacha",
        "price_conditions_tg": "аз 1 850 то 4 000 ₽ дар як сол",
        "price_conditions_kg": "жылына 1 850 - 4 000 ₽ баштап",
        "price_conditions_kz": "жылына 1 850 - 4 000 ₽ дейін"
    },
    "loans": {
        "title_uz": "Tezkor qarzlar",
        "title_tg": "Қарзҳои фаврӣ",
        "title_kg": "Тез насыялар",
        "title_kz": "Тез қарыздар",
        "short_description_uz": "Ishga ruxsatnomasi (patent) bo'lgan chet el fuqarolari uchun mikrokreditlar.",
        "short_description_tg": "Микроқарзҳо барои шаҳрвандони хориҷӣ бо патенти корӣ.",
        "short_description_kg": "Иштөөгө патенти бар чет өлкөлүк жарандар үчүн чакан насыялар.",
        "short_description_kz": "Жұмыс істеуге патенті бар шетелдік азаматтарға арналған шағын несиелер.",
        "full_description_uz": "Mikromoliya tashkilotlari (MFO) orqali qisqa muddatli mikrokreditlar berish. 2026-yilda ushbu bozor qarz oluvchilarni qarz botqog'idan himoya qilish va kiber-firibgarlikka qarshi kurashish uchun qat'iy tartibga solindi.",
        "full_description_tg": "Пешниҳоди микроқарзҳои кӯтоҳмуддат тавассути ташкилотҳои микромолиявӣ (МФО). Дар соли 2026 ин бозор барои ҳимояи қарзгирон аз чанголи қарз ва мубориза бо қаллобии киберӣ ба таври қатъӣ танзим карда шуд.",
        "full_description_kg": "Микрофинансылык уюмдар (МФО) аркылуу кыска мөөнөттүү чакан насыяларды берүү. 2026-жылы бул рынок карыз алуучуларды карыз спиралынан коргоо жана киберкылмыштуулукка каршы күрөшүү үчүн катуу жөнгө салынган.",
        "full_description_kz": "Микроқаржы ұйымдары (МҚҰ) арқылы қысқа мерзімді шағын несиелер беру. 2026 жылы бұл нарық қарыз алушыларды қарыз қамытынан қорғау және киберқылмыспен күресу үшін қатаң түрде реттелді.",
        "documents_required_uz": "Pasport asl nusxasi\nPasport tarjimasi\nBiometriya\nDaromadlar to'g'risida ma'lumotnoma (50,000 rubldan yuqori bo'lsa)",
        "documents_required_tg": "Асли шиноснома\nТарҷумаи шиноснома\nБиометрия\nМаълумотнома дар бораи даромад (барои маблағи зиёда аз 50000 рубл)",
        "documents_required_kg": "Паспорттун түп нускасы\nПаспорттун котормосу\nБиометрия\nКиреше жөнүндө маалымкат (50 000 рублдан жогору болсо)",
        "documents_required_kz": "Төлқұжат түпнұсқасы\nТөлқұжат аудармасы\nБиометрия\nТабыс туралы анықтама (50 000 рубльден жоғары сома болса)",
        "processing_time_uz": "1-3 kun",
        "processing_time_tg": "1-3 рӯз",
        "processing_time_kg": "1-3 күн",
        "processing_time_kz": "1-3 күн",
        "price_conditions_uz": "Shaxsiy tartibda",
        "price_conditions_tg": "Инфиродӣ",
        "price_conditions_kg": "Жеке тартипте",
        "price_conditions_kz": "Жекелей"
    },
    "transfers": {
        "title_uz": "Uyga o'tkazmalar",
        "title_tg": "Интиқоли пул ба хона",
        "title_kg": "Үйгө акча которуулар",
        "title_kz": "Үйге ақша аударымдары",
        "short_description_uz": "MDH mamlakatlariga hamyonbop kurslarda pul o'tkazmalari.",
        "short_description_tg": "Интиқоли пул ба кишварҳои ИДМ бо қурби муфид тавассути шарикони боэътимод.",
        "short_description_kg": "КМШ өлкөлөрүнө пайдалуу курс менен текшерилген өнөктөштөр аркылуу акча которуулар.",
        "short_description_kz": "ТМД елдеріне тиімді курспен тексерілген серіктестер арқылы ақша аударымдары.",
        "full_description_uz": "MDH mamlakatlariga qonuniy transchegaraviy o'tkazmalar xizmati, hozirda ikkita asosiy kanalga tayanadi: Tezkor To'lovlar Tizimi (SBP) va 'Zolotaya Korona' kabi klassik pul o'tkazmalari tizimlari. SBP orqali o'tkazmalar telefon raqami bo'yicha to'g'ridan-to'g'ri milliy to'lov tizimlari kartalariga yuborish imkonini beradi — masalan, 'Belkart' (Belarus), 'Korti Milli' (Tojikiston) yoki 'ArCa' (Armaniston).",
        "full_description_tg": "Хадамоти қонунии интиқоли пули фаромарзӣ ба кишварҳои ИДМ, ки ҳоло ба ду канали асосӣ асос ёфтааст: Системаи пардохтҳои фаврӣ (СБП) ва системаҳои классикии интиқоли пул ба монанди «Золотая Корона». Интиқол тавассути СБП имкон медиҳад, ки пул тавассути рақами телефон мустақиман ба кортҳои системаҳои миллии пардохт — масалан, «Белкарт» (Беларус), «Корти Миллӣ» (Тоҷикистон) ё «ArCa» (Арманистон) фиристода шавад.",
        "full_description_kg": "КМШ өлкөлөрүнө мыйзамдуу акча которуу кызматы, учурда ал эки негизги каналга таянат: Ыкчам төлөмдөр системасы (СБП) жана 'Золотая Корона' сыяктуу классикалык акча которуу системалары. СБП аркылуу которуулар телефон номери боюнча түздөн-түз улуттук төлөм системаларынын карталарына — мисалы, 'Белкарт' (Беларусь), 'Корти Милли' (Тажикстан) же 'ArCa' (Армения) карталарына акча жөнөтүүгө мүмкүндүк берет.",
        "full_description_kz": "ТМД елдеріне заңды трансшекаралық аударымдар қызметі, қазіргі уақытта ол екі негізгі арнаға негізделген: Жылдам төлемдер жүйесі (СБП) және «Золотая Корона» сияқты классикалық ақша аудару жүйелері. СБП арқылы аударымдар телефон нөмірі бойынша тікелей ұлттық төлем жүйелерінің карталарына — мысалы, «Белкарт» (Беларусь), «Корти Милли» (Тәжікстан) немесе «ArCa» (Армения) карталарына ақша жіберуге мүмкіндік береді.",
        "documents_required_uz": "Pasport asl nusxasi\nPasport tarjimasi",
        "documents_required_tg": "Асли шиноснома\nТарҷумаи шиноснома",
        "documents_required_kg": "Паспорттун түп нускасы\nПаспорттун котормосу",
        "documents_required_kz": "Төлқұжат түпнұсқасы\nТөлқұжат аудармасы",
        "processing_time_uz": "Shaxsiy tartibda",
        "processing_time_tg": "Инфиродӣ",
        "processing_time_kg": "Жеке тартипте",
        "processing_time_kz": "Жекелей",
        "price_conditions_uz": "Shaxsiy tartibda",
        "price_conditions_tg": "Инфиродӣ",
        "price_conditions_kg": "Жеке тартипте",
        "price_conditions_kz": "Жекелей"
    },
    "housing": {
        "title_uz": "Turar-joy topishda yordam",
        "title_tg": "Кӯмак дар ёфтани манзил",
        "title_kg": "Турак жай табууга көмөктөшүү",
        "title_kz": "Тұрғын үй табуға көмектесу",
        "short_description_uz": "Ish joyingizga yaqin yotoqxonalar va kvartiralar topish. Qonuniy ro'yxatdan o'tish.",
        "short_description_tg": "Интихоби хобгоҳҳо ва квартираҳо дар наздикии ҷои кори шумо. Бақайдгирии қонунӣ.",
        "short_description_kg": "Жумушуңузга жакын жатаканаларды жана батирлерди тандоо. Мыйзамдуу каттоо.",
        "short_description_kz": "Жұмыс орныңызға жақын жатақханалар мен пәтерлерді таңдау. Заңды тіркеу.",
        "full_description_uz": "Mulki egalari munitsipal filtrdan o'tishga tayyor bo'lgan va xodimni rasmiy migratsiya hisobiga qo'yishni kafolatlaydigan qonuniy yotoqxonalar, xostellar va kvartiralarni tanlashni o'z ichiga oladi.",
        "full_description_tg": "Интихоби хобгоҳҳои қонунӣ, хостелҳо ва квартираҳоро дар бар мегирад, ки дар он соҳибкорон омодаанд аз филтри мунисипалӣ гузаранд ва бақайдгирии расмии муҳоҷирати кормандро кафолат медиҳанд.",
        "full_description_kg": "Менчик ээлери муниципалдык чыпкадан өтүүгө даяр болгон жана кызматкерди расмий миграциялык каттоого коюуга кепилдик берген мыйзамдуу жатаканаларды, хостелдерди жана батирлерди тандоону камтыйт.",
        "full_description_kz": "Меншік иелері муниципалдық сүзгіден өтуге дайын және қызметкерді ресми көші-қон есебіне қоюға кепілдік беретін заңды жатақханаларды, хостелдерді және пәтерлерді таңдауды қамтиды.",
        "documents_required_uz": "Mahalliy hokimiyat organlaridan (munitsipalitetdan) dastlabki maxsus ruxsatnoma\nPasport asl nusxasi\nPasport tarjimasi\nMigratsiya kartasi\nSNILS",
        "documents_required_tg": "Иҷозати пешакии махсус аз мақомоти маҳаллии ҳокимияти давлатӣ (мунисипалитет)\nАсли шиноснома\nТарҷумаи шиноснома\nКорти муҳоҷиратӣ\nСНИЛС",
        "documents_required_kg": "Жергиликтүү өз алдынча башкаруу органдарынан (муниципалитеттен) алдын ала атайын уруксат\nПаспорттун түп нускасы\nПаспорттун котормосу\nМиграциялык карта\nСНИЛС",
        "documents_required_kz": "Жергілікті өзін-өзі басқару органдарынан (муниципалитеттен) алдын ала арнайы рұқсат\nТөлқұжат түпнұсқасы\nТөлқұжат аудармасы\nКөші-қон картасы\nСНИЛС",
        "processing_time_uz": "Shaxsiy tartibda",
        "processing_time_tg": "Инфиродӣ",
        "processing_time_kg": "Жеке тартипте",
        "processing_time_kz": "Жекелей",
        "price_conditions_uz": "Shaxsiy tartibda",
        "price_conditions_tg": "Инфиродӣ",
        "price_conditions_kg": "Жеке тартипте",
        "price_conditions_kz": "Жекелей"
    },
    "snils": {
        "title_uz": "SNILS (СНИЛС)",
        "title_tg": "СНИЛС",
        "title_kg": "СНИЛС",
        "title_kz": "Зейнетақы куәлігі (СНИЛС)",
        "short_description_uz": "Ishlash va ijtimoiy to'lovlar uchun shaxsiy sug'urta raqami.",
        "short_description_tg": "Рақами суғуртаи инфиродӣ барои кор ва пардохтҳои иҷтимоӣ.",
        "short_description_kg": "Жумуш жана социалдык төлөмдөр үчүн жеке камсыздандыруу номери.",
        "short_description_kz": "Жұмыс және әлеуметтік төлемдер үшін жеке сақтандыру нөмірі.",
        "full_description_uz": "Rasmiy ishga joylashish, nafaqalar olish va davlat xizmatlaridan foydalanish uchun SNILSni tezda olishga yordam beramiz.",
        "full_description_tg": "Мо барои зуд гирифтани СНИЛС барои кори расмӣ, гирифтани кумакпулиҳо ва дастрасӣ ба хидматҳои давлатӣ кӯмак мекунем.",
        "full_description_kg": "Расмий ишке орношуу, жөлөк пул алуу жана мамлекеттик кызматтарга жетүү үчүн СНИЛСти тез арада алууга көмөктөшөбүз.",
        "full_description_kz": "Ресми жұмысқа орналасу, жәрдемақы алу және мемлекеттік қызметтерге қол жеткізу үшін СНИЛС-ті тез арада алуға көмектесеміз.",
        "documents_required_uz": "Pasport, Pasportning notarial tarjimasi",
        "documents_required_tg": "Шиноснома, Тарҷумаи нотариалии шиноснома",
        "documents_required_kg": "Паспорт, Паспорттун нотариалдык котормосу",
        "documents_required_kz": "Төлқұжат, Төлқұжаттың нотариалды аудармасы",
        "processing_time_uz": "1-3 ish kuni",
        "processing_time_tg": "1-3 рӯзи корӣ",
        "processing_time_kg": "1-3 жумушчу күн",
        "processing_time_kz": "1-3 жұмыс күні",
        "price_conditions_uz": "500 ₽ dan boshlab",
        "price_conditions_tg": "Аз 500 ₽",
        "price_conditions_kg": "500 ₽ баштап",
        "price_conditions_kz": "500 ₽ бастап"
    },
    "inn": {
        "title_uz": "INN (ИНН / STIR)",
        "title_tg": "ИНН",
        "title_kg": "ИНН",
        "title_kz": "ЖСН (ИНН)",
        "short_description_uz": "Qonuniy ishlash uchun soliq to'lovchining shaxsiy raqami.",
        "short_description_tg": "Рақами инфиродии андозсупоранда барои кори қонунӣ.",
        "short_description_kg": "Мыйзамдуу иштөө үчүн салык төлөөчүнүн жеке номери.",
        "short_description_kz": "Заңды жұмыс істеу үшін салық төлеушінің жеке нөмірі.",
        "full_description_uz": "Soliqlarni to'lash va patent yoki mehnat shartnomasini rasmiy rasmiylashtirish uchun soliq inspektsiyasida INN rasmiylashtirish.",
        "full_description_tg": "Бақайдгирии ИНН дар нозироти андоз барои пардохти андозҳо ва бақайдгирии расмии патент ё шартномаи меҳнатӣ.",
        "full_description_kg": "Салыктарды төлөө жана патентти же эмгек келишимин расмий каттоо үчүн салык инспекциясында ИННди каттоо.",
        "full_description_kz": "Салық төлеу және патентті немесе еңбек шартын ресми ресімдеу үшін салық инспекциясында ЖСН (ИНН) ресімдеу.",
        "documents_required_uz": "Pasport, Ro'yxatdan o'tish (migratsiya hisobi)",
        "documents_required_tg": "Шиноснома, Бақайдгирӣ (ҳисоби муҳоҷиратӣ)",
        "documents_required_kg": "Паспорт, Каттоо (миграциялык каттоо)",
        "documents_required_kz": "Төлқұжат, Тіркеу (көші-қон есебі)",
        "processing_time_uz": "5 ish kunigacha",
        "processing_time_tg": "То 5 рӯзи корӣ",
        "processing_time_kg": "5 жумушчу күнгө чейин",
        "processing_time_kz": "5 жұмыс күніне дейін",
        "price_conditions_uz": "500 ₽ dan boshlab",
        "price_conditions_tg": "Аз 500 ₽",
        "price_conditions_kg": "500 ₽ баштап",
        "price_conditions_kz": "500 ₽ бастап"
    },
    "patent": {
        "title_uz": "Ishga ruxsatnoma (Patent)",
        "title_tg": "Патент барои кор",
        "title_kg": "Иштөөгө патент",
        "title_kz": "Жұмысқа патент",
        "short_description_uz": "Vizasiz MDH davlatlari fuqarolari uchun Rossiyada ishlash uchun asosiy hujjat.",
        "short_description_tg": "Ҳуҷҷати асосӣ барои кори қонунӣ дар Русия барои шаҳрвандони кишварҳои бевизаи ИДМ.",
        "short_description_kg": "Визасыз КМШ өлкөлөрүнүн жарандары үчүн РФда мыйзамдуу иштөө үчүн негизги документ.",
        "short_description_kz": "Визасыз ТМД елдерінің азаматтары үшін Ресейде заңды жұмыс істеуге арналған негізгі құжат.",
        "full_description_uz": "Patent olishda to'liq hamrohlik: hujjatlarni tayyorlash, MMCga yozilish, tibbiy ko'rikdan o'tishda yordam.",
        "full_description_tg": "Ҳамроҳии комил дар гирифтани патент: омода кардани ҳуҷҷатҳо, сабти ном дар ММЦ, кӯмак дар гузаштан аз муоинаи тиббӣ.",
        "full_description_kg": "Патент алууда толук коштоо: документтерди даярдоо, ММЦге жазылуу, медициналык кароодон өтүүгө көмөктөшүү.",
        "full_description_kz": "Патент алуда толық сүйемелдеу: құжаттарды дайындау, ММЦ-ге жазылу, медициналық тексеруден өтуге көмектесу.",
        "documents_required_uz": "Pasport, Migratsiya kartasi (maqsad: ish), Ro'yxatdan o'tish",
        "documents_required_tg": "Шиноснома, Корти муҳоҷиратӣ (мақсад: кор), Бақайдгирӣ",
        "documents_required_kg": "Паспорт, Миграциялык карта (максаты: иш), Каттоо",
        "documents_required_kz": "Төлқұжат, Көші-қон картасы (мақсаты: жұмыс), Тіркеу",
        "processing_time_uz": "10-20 kun",
        "processing_time_tg": "10-20 рӯз",
        "processing_time_kg": "10-20 күн",
        "processing_time_kz": "10-20 күн",
        "price_conditions_uz": "Shaxsiy tartibda",
        "price_conditions_tg": "Инфиродӣ",
        "price_conditions_kg": "Жеке тартипте",
        "price_conditions_kz": "Жекелей"
    },
    "green-card": {
        "title_uz": "Yashil karta",
        "title_tg": "Корти сабз",
        "title_kg": "Жашыл карта",
        "title_kz": "Жасыл карта",
        "short_description_uz": "Daktiloskopiya va suratga olishdan o'tganlik to'g'risidagi hujjat.",
        "short_description_tg": "Ҳуҷҷат дар бораи гузаштани дактилоскопия ва аксбардорӣ.",
        "short_description_kg": "Дактилоскопия жана сүрөткө түшүүдөн өткөндүгү жөнүндө документ.",
        "short_description_kz": "Дактилоскопия мен фотосуретке түсуден өткені туралы құжат.",
        "full_description_uz": "Har bir migrant uchun zarur bo'lgan majburiy daktiloskopik ro'yxatdan o'tish kartasini (Yashil karta) olishda yordam beramiz.",
        "full_description_tg": "Мо дар гирифтани корти бақайдгирии ҳатмии дактилоскопиӣ (Корти сабз), ки барои ҳар як муҳоҷир лозим аст, кӯмак мекунем.",
        "full_description_kg": "Ар бир мигрант үчүн зарыл болгон милдеттүү дактилоскопиялык каттоо картасын (Жашыл карта) алууга көмөктөшөбүз.",
        "full_description_kz": "Әрбір көшіп келуші үшін қажетті міндетті дактилоскопиялық тіркеу картасын (Жасыл карта) алуға көмектесеміз.",
        "documents_required_uz": "Pasport, Migratsiya kartasi",
        "documents_required_tg": "Шиноснома, Корти муҳоҷиратӣ",
        "documents_required_kg": "Паспорт, Миграциялык карта",
        "documents_required_kz": "Төлқұжат, Көші-қон картасы",
        "processing_time_uz": "1 ish kuni",
        "processing_time_tg": "1 рӯзи корӣ",
        "processing_time_kg": "1 жумушчу күн",
        "processing_time_kz": "1 жұмыс күні",
        "price_conditions_uz": "1000 ₽ dan boshlab",
        "price_conditions_tg": "Аз 1000 ₽",
        "price_conditions_kg": "1000 ₽ баштап",
        "price_conditions_kz": "1000 ₽ бастап"
    },
    "gosuslugi": {
        "title_uz": "Gosuslugi (Davlat xizmatlari)",
        "title_tg": "Госуслуги",
        "title_kg": "Госуслуги",
        "title_kz": "Госуслуги",
        "short_description_uz": "Gosuslugi tizimida ro'yxatdan o'tish va shaxsni tasdiqlash.",
        "short_description_tg": "Бақайдгирӣ ва тасдиқи шахсият дар системаи Госуслуги.",
        "short_description_kg": "Госуслуги системасында каттоо жана өздүгүн тастыктоо.",
        "short_description_kz": "Госуслуги жүйесінде тіркелу және жеке басын растау.",
        "full_description_uz": "Sizga barcha davlat xizmatlaridan onlayn foydalanish imkonini berish uchun hisob qaydnomasini yaratamiz va shaxsni tasdiqlaymiz: jarimalardan tortib shifokor qabuliga yozilishgacha.",
        "full_description_tg": "Мо ҳисоби корбарӣ месозем ва шахсиятро тасдиқ мекунем, то шумо тавонед аз ҳама хидматҳои давлатӣ онлайн истифода баред: аз ҷаримаҳо то сабти ном ба духтур.",
        "full_description_kg": "Сизге бардык мамлекеттик кызматтарды онлайн колдонуу мүмкүнчүлүгүн берүү үчүн каттоо эсебин түзөбүз жана өздүгүңүздү тастыктайбыз: айып пулдардан баштап дарыгерге жазылууга чейин.",
        "full_description_kz": "Барлық мемлекеттік қызметтерді онлайн пайдалана алуыңыз үшін есеп жазуын құрамыз және жеке басыңызды растаймыз: айыппұлдардан бастап дәрігерге жазылуға дейін.",
        "documents_required_uz": "Pasport, SNILS, Rossiya telefon raqami",
        "documents_required_tg": "Шиноснома, СНИЛС, Рақами телефони русӣ",
        "documents_required_kg": "Паспорт, СНИЛС, Россиялык телефон номери",
        "documents_required_kz": "Төлқұжат, СНИЛС, Ресейлік телефон нөмірі",
        "processing_time_uz": "15 daqiqa",
        "processing_time_tg": "15 дақиқа",
        "processing_time_kg": "15 мүнөт",
        "processing_time_kz": "15 минут",
        "price_conditions_uz": "Bepul",
        "price_conditions_tg": "Ройгон",
        "price_conditions_kg": "Акысыз",
        "price_conditions_kz": "Тегін"
    },
    "docs-audit": {
        "title_uz": "Hujjatlarni tekshirish",
        "title_tg": "Санҷиши ҳуҷҷатҳо",
        "title_kg": "Документтерди текшерүү",
        "title_kz": "Құжаттарды тексеру",
        "short_description_uz": "Hujjatlaringizni haqiqiyligi va xatolar bor-yo'qligini tekshiramiz.",
        "short_description_tg": "Мо ҳуҷҷатҳои шуморо барои асолат ва хатогиҳо месанҷем.",
        "short_description_kg": "Биз сиздин документтериңиздин түп нускалыгын жана каталарын текшеребиз.",
        "short_description_kz": "Біз сіздің құжаттарыңыздың түпнұсқалығын және қателерін тексереміз.",
        "full_description_uz": "Sizning migratsiya maqomingiz auditi: deportatsiyani oldini olish uchun patent, ro'yxatdan o'tish va cheklarni rasmiy reestrlarda tekshiramiz.",
        "full_description_tg": "Аудити мақоми муҳоҷирати шумо: мо патент, бақайдгирӣ ва квитансияҳоро дар феҳристҳои расмӣ месанҷем, то аз депортатсия пешгирӣ кунем.",
        "full_description_kg": "Сиздин миграциялык статусуңуздун аудити: депортациядан качуу үчүн патентти, каттоону жана чектерди расмий реестрлерде текшеребиз.",
        "full_description_kz": "Көші-қон статусыңыздың аудиті: депортацияны болдырмау үшін патентті, тіркеуді және чектерді ресми тізілімдерде тексереміз.",
        "documents_required_uz": "Barcha mavjud hujjatlar",
        "documents_required_tg": "Ҳамаи ҳуҷҷатҳои мавҷуда",
        "documents_required_kg": "Бардык бар болгон документтер",
        "documents_required_kz": "Барлық бар құжаттар",
        "processing_time_uz": "10-30 daqiqa",
        "processing_time_tg": "10-30 дақиқа",
        "processing_time_kg": "10-30 мүнөт",
        "processing_time_kz": "10-30 минут",
        "price_conditions_uz": "Konsultatsiya",
        "price_conditions_tg": "Машварат",
        "price_conditions_kg": "Консультация",
        "price_conditions_kz": "Консультация"
    },
    "flights": {
        "title_uz": "Aviabiletlar",
        "title_tg": "Чиптаҳои ҳавопаймо",
        "title_kg": "Авиабилеттер",
        "title_kz": "Авиабилеттер",
        "short_description_uz": "MDH fuqarolari uchun hamyonbop narxlarda biletlar qidirish va sotib olish.",
        "short_description_tg": "Ҷустуҷӯ ва хариди чиптаҳо бо нархҳои муфид барои шаҳрвандони ИДМ.",
        "short_description_kg": "КМШ жарандары үчүн пайдалуу тарифтер менен билеттерди издөө жана сатып алуу.",
        "short_description_kz": "ТМД азаматтары үшін тиімді тарифтермен билеттерді іздеу және сатып алу.",
        "full_description_uz": "Uyga yoki Rossiya bo'ylab chiptalarni tanlash va sotib olishda yordam beramiz. Ustamalarsiz, barcha ma'lumotlarni tekshirgan holda.",
        "full_description_tg": "Мо дар интихоб ва хариди чиптаҳо ба хона ё дар саросари Русия кӯмак мекунем. Бе иловапулӣ, бо санҷиши ҳамаи маълумотҳо.",
        "full_description_kg": "Үйгө же Россия боюнча билеттерди тандап, сатып алууга көмөктөшөбүз. Кошумча баасыз, бардык маалыматтарды текшерүү менен.",
        "full_description_kz": "Үйге немесе Ресей бойынша билеттерді таңдауға және сатып алуға көмектесеміз. Үстемеақысыз, барлық деректерді тексере отырып.",
        "documents_required_uz": "Pasport",
        "documents_required_tg": "Шиноснома",
        "documents_required_kg": "Паспорт",
        "documents_required_kz": "Төлқұжат",
        "processing_time_uz": "Zudlik bilan",
        "processing_time_tg": "Дарҳол",
        "processing_time_kg": "Тез арада",
        "processing_time_kz": "Лезде",
        "price_conditions_uz": "Aviakompaniya narxida",
        "price_conditions_tg": "Бо нархи ширкатҳои ҳавопаймоӣ",
        "price_conditions_kg": "Авиакомпаниялардын баасында",
        "price_conditions_kz": "Әуекомпаниялардың бағасымен"
    }
}


def run():
    count = 0
    print("Начинаю обновление переводов для услуг...")

    for slug, fields in translations_data.items():
        try:
            service = ServiceItem.objects.get(slug=slug)
            for field_name, value in fields.items():
                setattr(service, field_name, value)
            service.save()
            print(f"✅ Обновлено: {slug}")
            count += 1
        except ServiceItem.DoesNotExist:
            print(f"⚠️ Услуга не найдена (пропуск): {slug}")
        except Exception as e:
            print(f"❌ Ошибка при обновлении {slug}: {e}")
    print(f"\nГотово! Обновлено услуг: {count} из {len(translations_data)}")


if __name__ == "__main__":
    run()