# Generated by Django 6.0.3 on 2026-03-07 17:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('job', 'Отклик на вакансию'), ('housing', 'Подобрать жильё'), ('service', 'Оформить документ/сервис')], max_length=20, verbose_name='Тип заявки')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано модератором')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
            ],
            options={
                'verbose_name': 'Лид / Заявка',
                'verbose_name_plural': 'Лиды / Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL (ЧПУ)')),
                ('service_type', models.CharField(choices=[('docs', 'Документы'), ('finance', 'Финансы и Сервисы'), ('housing', 'Жильё')], max_length=20, verbose_name='Тип услуги')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание (для карточки)')),
                ('full_description', models.TextField(verbose_name='Кому это нужно и что это')),
                ('documents_required', models.TextField(blank=True, verbose_name='Какие документы нужны')),
                ('processing_time', models.CharField(blank=True, max_length=100, verbose_name='Сроки')),
                ('price_conditions', models.CharField(blank=True, max_length=255, verbose_name='Стоимость/Условия')),
                ('is_partner_service', models.BooleanField(default=False, verbose_name='Партнёрский сервис (дисклеймер)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга/Сервис',
                'verbose_name_plural': 'Услуги и Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL (ЧПУ)')),
                ('city', models.CharField(max_length=100, verbose_name='Город/Регион')),
                ('salary', models.CharField(max_length=100, verbose_name='Ставка/Доход')),
                ('schedule', models.CharField(max_length=100, verbose_name='График работы')),
                ('housing_provided', models.BooleanField(default=False, verbose_name='Жильё предоставляется')),
                ('meals_provided', models.BooleanField(default=False, verbose_name='Питание предоставляется')),
                ('docs_included', models.BooleanField(default=False, verbose_name='Документы "под ключ"')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor (Контент)'), ('moderator', 'Moderator (Заявки)'), ('reviewer', 'Reviewer (Юрист)'), ('viewer', 'Viewer (Просмотр)')], default='viewer', max_length=20, verbose_name='Роль пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL (ЧПУ)')),
                ('lead', models.TextField(blank=True, help_text='Если пусто — сгенерируется из текста', verbose_name='Короткое описание (Анонс)')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('category', models.CharField(choices=[('documents', 'Документы'), ('work', 'Работа'), ('housing', 'Жильё'), ('laws', 'Законы'), ('important', 'Важно'), ('stories', 'Истории')], max_length=20, verbose_name='Тег/Категория')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha'), ('tg', 'Тоҷикӣ'), ('kg', 'Кыргызча'), ('kz', 'Қазақша')], default='ru', max_length=5, verbose_name='Язык')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_covers/%Y/%m/', verbose_name='Обложка')),
                ('show_question_btn', models.BooleanField(default=False, verbose_name='Кнопка "Задать вопрос в Telegram"')),
                ('show_consult_btn', models.BooleanField(default=False, verbose_name='Кнопка "Получить консультацию"')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('published', 'Опубликовано'), ('archive', 'Архив')], default='draft', max_length=20, verbose_name='Статус публикации')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Можно запланировать на будущее', verbose_name='Дата публикации')),
                ('source', models.CharField(blank=True, help_text='Например: telegram_bot', max_length=50, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='ID внешнего поста (Telegram/VK)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Заголовок (Title)')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Описание (Description)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор/Редактор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
