# Generated by Django 6.0.3 on 2026-03-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Админ)'), ('editor', 'Editor (Контент)'), ('moderator', 'Moderator (Заявки)'), ('reviewer', 'Reviewer (Юрист)'), ('viewer', 'Viewer (Просмотр)')], default='viewer', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
