# Generated by Django 6.0.3 on 2026-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID'),
        ),
    ]
