# Generated by Django 6.0.3 on 2026-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='service_type',
            field=models.CharField(choices=[('free', 'Бесплатные услуги'), ('prep', 'Подготовка документов'), ('assist', 'Помощь и сопровождение')], max_length=20, verbose_name='Тип услуги'),
        ),
    ]
