# Generated by Django 6.0.3 on 2026-03-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение услуги'),
        ),
    ]
