# Generated by Django 6.0.3 on 2026-03-22 20:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_covers/%Y/%m/', validators=[core.models.News.validate_aspect_ratio], verbose_name='Обложка'),
        ),
    ]
