# Generated by Django 6.0.3 on 2026-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_news_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='documents_required_kg',
            field=models.TextField(blank=True, verbose_name='Какие документы нужны (KG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='documents_required_kz',
            field=models.TextField(blank=True, verbose_name='Какие документы нужны (KZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='documents_required_tg',
            field=models.TextField(blank=True, verbose_name='Какие документы нужны (TG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='documents_required_uz',
            field=models.TextField(blank=True, verbose_name='Какие документы нужны (UZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='full_description_kg',
            field=models.TextField(blank=True, verbose_name='Кому это нужно и что это (KG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='full_description_kz',
            field=models.TextField(blank=True, verbose_name='Кому это нужно и что это (KZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='full_description_tg',
            field=models.TextField(blank=True, verbose_name='Кому это нужно и что это (TG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='full_description_uz',
            field=models.TextField(blank=True, verbose_name='Кому это нужно и что это (UZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='price_conditions_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стоимость/Условия (KG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='price_conditions_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стоимость/Условия (KZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='price_conditions_tg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стоимость/Условия (TG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='price_conditions_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стоимость/Условия (UZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='processing_time_kg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сроки (KG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='processing_time_kz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сроки (KZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='processing_time_tg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сроки (TG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='processing_time_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сроки (UZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='short_description_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (KG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='short_description_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (KZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='short_description_tg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (TG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (UZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название услуги (KG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название услуги (KZ)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_tg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название услуги (TG)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название услуги (UZ)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='documents_required',
            field=models.TextField(blank=True, verbose_name='Какие документы нужны (RU)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='full_description',
            field=models.TextField(verbose_name='Кому это нужно и что это (RU)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='price_conditions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стоимость/Условия (RU)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='processing_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сроки (RU)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название услуги (RU)'),
        ),
    ]
