# Generated by Django 6.0.3 on 2026-03-23 19:35

from django.db import migrations, models


def update_news_language(apps, schema_editor):
    News = apps.get_model('core', 'News')
    News.objects.filter(language='kz').update(language='kk')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serviceitem_documents_required_kg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceitem',
            old_name='documents_required_kz',
            new_name='documents_required_kk',
        ),
        migrations.RenameField(
            model_name='serviceitem',
            old_name='full_description_kz',
            new_name='full_description_kk',
        ),
        migrations.RenameField(
            model_name='serviceitem',
            old_name='price_conditions_kz',
            new_name='price_conditions_kk',
        ),
        migrations.RenameField(
            model_name='serviceitem',
            old_name='processing_time_kz',
            new_name='processing_time_kk',
        ),
        migrations.RenameField(
            model_name='serviceitem',
            old_name='short_description_kz',
            new_name='short_description_kk',
        ),
        migrations.RenameField(
            model_name='serviceitem',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha'), ('tg', 'Тоҷикӣ'), ('kg', 'Кыргызча'), ('kk', 'Қазақша')], default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.RunPython(update_news_language),
    ]
